name: belajar_dart_unit_test
description: A simple command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
environment:
  sdk: ^3.1.2

# Add regular dependencies here.
# dependencies:
# path: ^1.8.0
dev_dependencies:
  build_runner: ^2.4.7
  lints: ^2.0.0
  mockito: ^5.4.4
  test: ^1.25.0
dependencies:
  http: ^1.1.0
